[package]
name = "message-to-console"
version = "0.1.0"
edition = "2024"

[dependencies]
amqprs = { version = "2.1.2" }
async-trait = "0.1.89"
chrono = "0.4.42"
tokio = { version = "1.47.1", features = ["signal"] }
